name: filternet_app
description: A simple utility to check whether the given url/domain is blocked in Iran.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Utilities
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.19.0

  # State Management
  provider: ^6.1.2

  # Networking & Core Logic
  http: ^1.2.1
  share_plus: ^9.0.0
  # dart_ping has been REMOVED to ensure build stability

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Dev Dependencies
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
