name: Build & Release FilterNet App

on:
  push:
    branches: [ main ]

jobs:
  # Job to build the Android APK
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate Hive Adapters
        run: flutter pub run build_runner build --delete-conflicting-outputs

      # The problematic 'sed' command has been REMOVED from here.

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload APK artifact for release job
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  # Job to build the Windows Executable
  build_windows:
    name: Build Windows Executable
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get

      - name: Generate Hive Adapters
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Windows Executable
        run: flutter build windows --release

      - name: Upload Windows artifact for release job
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: build/windows/runner/Release/

  # Job to create a GitHub Release
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build_android, build_windows]
    permissions:
      contents: write
    steps:
      - name: Download Android APK artifact
        uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: artifacts/

      - name: Download Windows Build artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-release
          path: artifacts/windows-release/

      - name: Zip the Windows release folder
        run: zip -r ../windows-release.zip .
        working-directory: artifacts/windows-release

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: FilterNet App v${{ github.run_number }}
          body: |
            نسخه خودکار اپلیکیشن فیلترنت.
            این نسخه شامل فایل‌های نصبی برای اندروید و ویندوز است.
          files: |
            artifacts/app-release.apk
            artifacts/windows-release.zip
