name: Create Flutter Project Structure

# This allows you to run this workflow manually from the Actions tab
on: workflow_dispatch

jobs:
  create-flutter-app:
    name: Initialize Flutter Project
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the empty repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Flutter SDK
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 3. Run 'flutter create' in the current directory
      # The '.' is important! It creates the project in the root of the repository.
      - name: Create Flutter project
        run: flutter create --project-name filternet_app .

      # 4. Commit the new files back to the repository
      - name: Commit and push generated files
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "feat: Initialize Flutter project structure via Actions"
          git push
